# Generated by Django 4.2.3 on 2023-08-12 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
