# Generated by Django 4.2.3 on 2023-07-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="prise",
            new_name="price",
        ),
    ]
