# Generated by Django 4.2.3 on 2023-08-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_blog_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="creation_date",
            field=models.DateField(auto_now=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="modified_date",
            field=models.DateField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
