# Generated by Django 4.2.3 on 2023-08-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="current_version",
            field=models.BooleanField(
                default=False, verbose_name="признак текущей версии"
            ),
        ),
    ]
