# Generated by Django 4.2.3 on 2023-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publishing_flag",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
